from __future__ import annotations

from nbadb.cli.commands import (  # noqa: F401
    ask,
    audit_models,
    backfill,
    chat,
    daily,
    docs_autogen,
    download,
    endpoint_adequacy_scorecard,
    endpoint_support_matrix,
    export,
    extract_completeness,
    full,
    init,
    lint_sql,
    live_snapshot,
    metadata,
    migrate,
    monthly,
    scan,
    schema,
    status,
    table_year_coverage,
    upload,
)
