from __future__ import annotations

import polars as pl

from nbadb.schemas.registry import get_input_schema, get_output_schema
from nbadb.schemas.staging.player_support_matrix import (
    StagingCollegeRollupEastSchema,
    StagingCollegeRollupMidwestSchema,
    StagingCollegeRollupSouthSchema,
    StagingCollegeRollupWestSchema,
    StagingLeaguePlayerOnDetailsSchema,
    StagingPlayerCareerAllstarSchema,
    StagingPlayerCareerByCollegeRollupSchema,
    StagingPlayerCareerCollegeSchema,
    StagingPlayerCareerPostseasonSchema,
    StagingPlayerCareerRegularSchema,
    StagingPlayerCareerTotalAllstarSchema,
    StagingPlayerCareerTotalCollegeSchema,
    StagingPlayerCareerTotalPostseasonSchema,
    StagingPlayerCareerTotalRegularSchema,
    StagingPlayerCollegeRollupSchema,
    StagingPlayerCollegeSchema,
    StagingPlayerCompareIndividualSchema,
    StagingPlayerCompareOverallSchema,
    StagingPlayerCompareSchema,
    StagingPlayerGameLogsSchema,
    StagingPlayerGameLogsV2Schema,
    StagingPlayerGameStreakFinderSchema,
    StagingPlayerNextGamesSchema,
    StagingPlayerOnDetailsSchema,
    StagingPlayerProfileAllstarSchema,
    StagingPlayerProfileCareerHighsSchema,
    StagingPlayerProfileCollegeSchema,
    StagingPlayerProfileNextGameSchema,
    StagingPlayerProfilePostseasonSchema,
    StagingPlayerProfilePreseasonSchema,
    StagingPlayerProfileRanksPostseasonSchema,
    StagingPlayerProfileRanksRegularSchema,
    StagingPlayerProfileRegularSchema,
    StagingPlayerProfileSeasonHighsSchema,
    StagingPlayerProfileTotalAllstarSchema,
    StagingPlayerProfileTotalCollegeSchema,
    StagingPlayerProfileTotalPostseasonSchema,
    StagingPlayerProfileTotalPreseasonSchema,
    StagingPlayerProfileTotalRegularSchema,
    StagingPlayerPtPassReceivedSchema,
    StagingPlayerPtPassSchema,
    StagingPlayerPtRebDistanceSchema,
    StagingPlayerPtRebOverallSchema,
    StagingPlayerPtRebSchema,
    StagingPlayerPtRebShotDistSchema,
    StagingPlayerPtRebShotTypeSchema,
    StagingPlayerPtShotDefendSchema,
    StagingPlayerPtShotsClosestDefSchema,
    StagingPlayerPtShotsDribbleSchema,
    StagingPlayerPtShotsGeneralSchema,
    StagingPlayerPtShotsOverallSchema,
    StagingPlayerPtShotsSchema,
    StagingPlayerPtShotsShotClockSchema,
    StagingPlayerPtShotsTouchTimeSchema,
    StagingPlayerSeasonRanksPostseasonSchema,
    StagingPlayerSeasonRanksRegularSchema,
    StagingPlayerStreakFinderSchema,
    StagingPlayerTrackingSchema,
    StagingPlayerVsPlayerSchema,
    StagingPvpOnOffCourtSchema,
    StagingPvpOverallSchema,
    StagingPvpPlayerInfoSchema,
    StagingPvpShotAreaOffSchema,
    StagingPvpShotAreaOnSchema,
    StagingPvpShotAreaOverallSchema,
    StagingPvpShotDistOffSchema,
    StagingPvpShotDistOnSchema,
    StagingPvpShotDistOverallSchema,
    StagingPvpVsPlayerInfoSchema,
    StagingWinProbPbpSchema,
)
from nbadb.schemas.star.player_support_matrix import (
    FactCollegeRollupSchema,
    FactPlayerCareerSchema,
    FactPlayerGameLogSchema,
    FactPlayerMatchupsSchema,
    FactPlayerNextGamesSchema,
    FactPlayerProfileSchema,
    FactPlayerPtPassSchema,
    FactPlayerPtRebDetailSchema,
    FactPlayerPtShotDefendSchema,
    FactPlayerPtShotsDetailSchema,
    FactPlayerPtTrackingSchema,
    FactPlayerSeasonRanksSchema,
    FactPlayerShootingSplitsDetailSchema,
)


def test_player_family_input_schema_registry_covers_remaining_support_keys() -> None:
    expected = {
        "stg_college_rollup_east": StagingCollegeRollupEastSchema,
        "stg_college_rollup_midwest": StagingCollegeRollupMidwestSchema,
        "stg_college_rollup_south": StagingCollegeRollupSouthSchema,
        "stg_college_rollup_west": StagingCollegeRollupWestSchema,
        "stg_player_on_details": StagingPlayerOnDetailsSchema,
        "stg_player_college": StagingPlayerCollegeSchema,
        "stg_player_career_allstar": StagingPlayerCareerAllstarSchema,
        "stg_player_career_by_college_rollup": StagingPlayerCareerByCollegeRollupSchema,
        "stg_player_career_college": StagingPlayerCareerCollegeSchema,
        "stg_player_career_postseason": StagingPlayerCareerPostseasonSchema,
        "stg_player_career_regular": StagingPlayerCareerRegularSchema,
        "stg_player_career_total_allstar": StagingPlayerCareerTotalAllstarSchema,
        "stg_player_career_total_college": StagingPlayerCareerTotalCollegeSchema,
        "stg_player_career_total_postseason": StagingPlayerCareerTotalPostseasonSchema,
        "stg_player_career_total_regular": StagingPlayerCareerTotalRegularSchema,
        "stg_player_college_rollup": StagingPlayerCollegeRollupSchema,
        "stg_player_compare": StagingPlayerCompareSchema,
        "stg_player_compare_individual": StagingPlayerCompareIndividualSchema,
        "stg_player_compare_overall": StagingPlayerCompareOverallSchema,
        "stg_player_game_logs": StagingPlayerGameLogsSchema,
        "stg_player_game_logs_v2": StagingPlayerGameLogsV2Schema,
        "stg_player_game_streak_finder": StagingPlayerGameStreakFinderSchema,
        "stg_player_next_games": StagingPlayerNextGamesSchema,
        "stg_player_profile_allstar": StagingPlayerProfileAllstarSchema,
        "stg_player_profile_career_highs": StagingPlayerProfileCareerHighsSchema,
        "stg_player_profile_college": StagingPlayerProfileCollegeSchema,
        "stg_player_profile_next_game": StagingPlayerProfileNextGameSchema,
        "stg_player_profile_postseason": StagingPlayerProfilePostseasonSchema,
        "stg_player_profile_preseason": StagingPlayerProfilePreseasonSchema,
        "stg_player_profile_ranks_postseason": StagingPlayerProfileRanksPostseasonSchema,
        "stg_player_profile_ranks_regular": StagingPlayerProfileRanksRegularSchema,
        "stg_player_profile_regular": StagingPlayerProfileRegularSchema,
        "stg_player_profile_season_highs": StagingPlayerProfileSeasonHighsSchema,
        "stg_player_profile_total_allstar": StagingPlayerProfileTotalAllstarSchema,
        "stg_player_profile_total_college": StagingPlayerProfileTotalCollegeSchema,
        "stg_player_profile_total_postseason": StagingPlayerProfileTotalPostseasonSchema,
        "stg_player_profile_total_preseason": StagingPlayerProfileTotalPreseasonSchema,
        "stg_player_profile_total_regular": StagingPlayerProfileTotalRegularSchema,
        "stg_player_pt_pass": StagingPlayerPtPassSchema,
        "stg_player_pt_pass_received": StagingPlayerPtPassReceivedSchema,
        "stg_player_pt_reb": StagingPlayerPtRebSchema,
        "stg_player_pt_reb_distance": StagingPlayerPtRebDistanceSchema,
        "stg_player_pt_reb_overall": StagingPlayerPtRebOverallSchema,
        "stg_player_pt_reb_shot_dist": StagingPlayerPtRebShotDistSchema,
        "stg_player_pt_reb_shot_type": StagingPlayerPtRebShotTypeSchema,
        "stg_player_pt_shot_defend": StagingPlayerPtShotDefendSchema,
        "stg_player_pt_shots": StagingPlayerPtShotsSchema,
        "stg_player_pt_shots_closest_def": StagingPlayerPtShotsClosestDefSchema,
        "stg_player_pt_shots_dribble": StagingPlayerPtShotsDribbleSchema,
        "stg_player_pt_shots_general": StagingPlayerPtShotsGeneralSchema,
        "stg_player_pt_shots_overall": StagingPlayerPtShotsOverallSchema,
        "stg_player_pt_shots_shot_clock": StagingPlayerPtShotsShotClockSchema,
        "stg_player_pt_shots_touch_time": StagingPlayerPtShotsTouchTimeSchema,
        "stg_player_season_ranks_postseason": StagingPlayerSeasonRanksPostseasonSchema,
        "stg_player_season_ranks_regular": StagingPlayerSeasonRanksRegularSchema,
        "stg_player_streak_finder": StagingPlayerStreakFinderSchema,
        "stg_player_tracking": StagingPlayerTrackingSchema,
        "stg_player_vs_player": StagingPlayerVsPlayerSchema,
        "stg_pvp_on_off_court": StagingPvpOnOffCourtSchema,
        "stg_pvp_overall": StagingPvpOverallSchema,
        "stg_pvp_player_info": StagingPvpPlayerInfoSchema,
        "stg_pvp_shot_area_off": StagingPvpShotAreaOffSchema,
        "stg_pvp_shot_area_on": StagingPvpShotAreaOnSchema,
        "stg_pvp_shot_area_overall": StagingPvpShotAreaOverallSchema,
        "stg_pvp_shot_dist_off": StagingPvpShotDistOffSchema,
        "stg_pvp_shot_dist_on": StagingPvpShotDistOnSchema,
        "stg_pvp_shot_dist_overall": StagingPvpShotDistOverallSchema,
        "stg_pvp_vs_player_info": StagingPvpVsPlayerInfoSchema,
        "stg_win_prob_pbp": StagingWinProbPbpSchema,
        "stg_league_player_on_details": StagingLeaguePlayerOnDetailsSchema,
    }

    for table_name, schema_cls in expected.items():
        assert get_input_schema(table_name) is schema_cls, table_name


def test_player_family_output_schema_registry_covers_remaining_support_tables() -> None:
    expected = {
        "fact_college_rollup": FactCollegeRollupSchema,
        "fact_player_career": FactPlayerCareerSchema,
        "fact_player_game_log": FactPlayerGameLogSchema,
        "fact_player_matchups": FactPlayerMatchupsSchema,
        "fact_player_next_games": FactPlayerNextGamesSchema,
        "fact_player_profile": FactPlayerProfileSchema,
        "fact_player_pt_pass": FactPlayerPtPassSchema,
        "fact_player_pt_reb_detail": FactPlayerPtRebDetailSchema,
        "fact_player_pt_shot_defend": FactPlayerPtShotDefendSchema,
        "fact_player_pt_shots_detail": FactPlayerPtShotsDetailSchema,
        "fact_player_pt_tracking": FactPlayerPtTrackingSchema,
        "fact_player_season_ranks": FactPlayerSeasonRanksSchema,
        "fact_player_shooting_splits_detail": FactPlayerShootingSplitsDetailSchema,
    }

    for table_name, schema_cls in expected.items():
        assert get_output_schema(table_name) is schema_cls, table_name


def test_player_family_schemas_validate_representative_rows() -> None:
    next_games = pl.DataFrame(
        {
            "game_id": ["0022401201"],
            "game_date": ["2025-04-17"],
            "game_time": ["7:30 PM ET"],
            "location": ["Home"],
            "player_team_id": [1610612744],
            "player_team_city": ["Golden State"],
            "player_team_nickname": ["Warriors"],
            "player_team_abbreviation": ["GSW"],
            "vs_team_id": [1610612738],
            "vs_team_city": ["Boston"],
            "vs_team_nickname": ["Celtics"],
            "vs_team_abbreviation": ["BOS"],
            "home_team_id": [1610612744],
            "visitor_team_id": [1610612738],
            "home_team_name": ["Golden State Warriors"],
            "visitor_team_name": ["Boston Celtics"],
            "home_team_abbreviation": ["GSW"],
            "visitor_team_abbreviation": ["BOS"],
            "home_team_nickname": ["Warriors"],
            "visitor_team_nickname": ["Celtics"],
            "home_wl": ["55-27"],
            "visitor_wl": ["61-21"],
            "season_type": ["Regular Season"],
        }
    )
    streak = pl.DataFrame(
        {
            "player_name_last_first": ["Curry, Stephen"],
            "player_id": [201939],
            "gamestreak": ["10+ PTS in 15 straight games"],
            "startdate": ["2025-03-01"],
            "enddate": ["2025-04-01"],
            "activestreak": ["Y"],
            "numseasons": [1],
            "lastseason": ["2024-25"],
            "firstseason": ["2024-25"],
        }
    )
    win_prob = pl.DataFrame(
        {
            "game_id": ["0022401201"],
            "event_num": [315],
            "home_pct": [0.742],
            "visitor_pct": [0.258],
            "home_pts": [104],
            "visitor_pts": [98],
            "home_score_margin": [6],
            "period": [4],
            "seconds_remaining": [32.4],
            "home_team_id": [1610612744],
            "home_team_abb": ["GSW"],
            "visitor_team_id": [1610612738],
            "visitor_team_abb": ["BOS"],
            "home_poss_ind": [1],
            "home_g": [1.0],
            "description": ["Stephen Curry makes 3PT jump shot"],
            "location": ["H"],
            "pctimestring": ["00:32.4"],
            "isvisible": [1],
        }
    )

    assert StagingPlayerNextGamesSchema.validate(next_games).height == 1
    assert FactPlayerNextGamesSchema.validate(next_games).height == 1
    assert StagingPlayerGameStreakFinderSchema.validate(streak).height == 1
    assert StagingWinProbPbpSchema.validate(win_prob).height == 1

    pt_pass = pl.DataFrame(
        {
            "player_id": [2544],
            "player_name_last_first": ["James, LeBron"],
            "team_name": ["Lakers"],
            "team_id": [1610612747],
            "team_abbreviation": ["LAL"],
            "pass_type": ["made"],
            "g": [82],
            "pass_to": [None],
            "pass_from": ["LeBron James"],
            "pass_teammate_player_id": [1627759],
            "frequency": [0.148],
            "pass": [312],
            "ast": [28],
            "fgm": [41],
            "fga": [88],
            "fg_pct": [0.466],
            "fg2m": [23],
            "fg2a": [40],
            "fg2_pct": [0.575],
            "fg3m": [18],
            "fg3a": [48],
            "fg3_pct": [0.375],
            "season_type": ["Regular Season"],
        }
    )
    shot_defend = pl.DataFrame(
        {
            "close_def_person_id": [2544],
            "gp": [20],
            "g": [20],
            "defense_category": ["Overall"],
            "freq": [0.33],
            "d_fgm": [4],
            "d_fga": [9],
            "d_fg_pct": [0.444],
            "normal_fg_pct": [0.49],
            "pct_plusminus": [-0.046],
            "season_type": ["Regular Season"],
        }
    )

    assert FactPlayerPtPassSchema.validate(pt_pass).height == 1
    assert FactPlayerPtShotDefendSchema.validate(shot_defend).height == 1
