from __future__ import annotations

import polars as pl

from nbadb.schemas.registry import get_input_schema, get_output_schema
from nbadb.schemas.staging.team_support_matrix import (
    StagingTapvpPlayersVsSchema,
    StagingTapvpTeamOffSchema,
    StagingTapvpTeamOnSchema,
    StagingTapvpTeamVsOffSchema,
    StagingTapvpTeamVsSchema,
    StagingTeamAndPlayersVsPlayersSchema,
    StagingTeamAndPlayersVsSchema,
    StagingTeamLineupsOverallSchema,
    StagingTeamLineupsSchema,
    StagingTeamPtPassReceivedSchema,
    StagingTeamPtPassSchema,
    StagingTeamPtRebDistanceSchema,
    StagingTeamPtRebOverallSchema,
    StagingTeamPtRebSchema,
    StagingTeamPtRebShotDistSchema,
    StagingTeamPtRebShotTypeSchema,
    StagingTeamPtShotsClosestDefSchema,
    StagingTeamPtShotsDribbleSchema,
    StagingTeamPtShotsGeneralSchema,
    StagingTeamPtShotsSchema,
    StagingTeamPtShotsShotClockSchema,
    StagingTeamPtShotsTouchTimeSchema,
    StagingTeamVsPlayerSchema,
    StagingTvpOnOffCourtSchema,
    StagingTvpOverallSchema,
    StagingTvpShotAreaOffSchema,
    StagingTvpShotAreaOnSchema,
    StagingTvpShotAreaOverallSchema,
    StagingTvpShotDistOffSchema,
    StagingTvpShotDistOnSchema,
    StagingTvpShotDistOverallSchema,
    StagingTvpVsPlayerOverallSchema,
)
from nbadb.schemas.star.team_support_matrix import (
    FactTeamLineupsDetailSchema,
    FactTeamMatchupsSchema,
)


def test_team_family_input_schema_registry_covers_remaining_support_keys() -> None:
    expected = {
        "stg_team_lineups": StagingTeamLineupsSchema,
        "stg_team_lineups_overall": StagingTeamLineupsOverallSchema,
        "stg_team_pt_pass": StagingTeamPtPassSchema,
        "stg_team_pt_pass_received": StagingTeamPtPassReceivedSchema,
        "stg_team_pt_reb": StagingTeamPtRebSchema,
        "stg_team_pt_reb_distance": StagingTeamPtRebDistanceSchema,
        "stg_team_pt_reb_overall": StagingTeamPtRebOverallSchema,
        "stg_team_pt_reb_shot_dist": StagingTeamPtRebShotDistSchema,
        "stg_team_pt_reb_shot_type": StagingTeamPtRebShotTypeSchema,
        "stg_team_pt_shots": StagingTeamPtShotsSchema,
        "stg_team_pt_shots_closest_def": StagingTeamPtShotsClosestDefSchema,
        "stg_team_pt_shots_dribble": StagingTeamPtShotsDribbleSchema,
        "stg_team_pt_shots_general": StagingTeamPtShotsGeneralSchema,
        "stg_team_pt_shots_shot_clock": StagingTeamPtShotsShotClockSchema,
        "stg_team_pt_shots_touch_time": StagingTeamPtShotsTouchTimeSchema,
        "stg_team_vs_player": StagingTeamVsPlayerSchema,
        "stg_tvp_on_off_court": StagingTvpOnOffCourtSchema,
        "stg_tvp_overall": StagingTvpOverallSchema,
        "stg_tvp_shot_area_off": StagingTvpShotAreaOffSchema,
        "stg_tvp_shot_area_on": StagingTvpShotAreaOnSchema,
        "stg_tvp_shot_area_overall": StagingTvpShotAreaOverallSchema,
        "stg_tvp_shot_dist_off": StagingTvpShotDistOffSchema,
        "stg_tvp_shot_dist_on": StagingTvpShotDistOnSchema,
        "stg_tvp_shot_dist_overall": StagingTvpShotDistOverallSchema,
        "stg_tvp_vs_player_overall": StagingTvpVsPlayerOverallSchema,
        "stg_team_and_players_vs": StagingTeamAndPlayersVsSchema,
        "stg_team_and_players_vs_players": StagingTeamAndPlayersVsPlayersSchema,
        "stg_tapvp_players_vs": StagingTapvpPlayersVsSchema,
        "stg_tapvp_team_off": StagingTapvpTeamOffSchema,
        "stg_tapvp_team_on": StagingTapvpTeamOnSchema,
        "stg_tapvp_team_vs": StagingTapvpTeamVsSchema,
        "stg_tapvp_team_vs_off": StagingTapvpTeamVsOffSchema,
    }

    for table_name, schema_cls in expected.items():
        assert get_input_schema(table_name) is schema_cls, table_name


def test_team_family_output_schema_registry_covers_remaining_support_tables() -> None:
    assert get_output_schema("fact_team_lineups_detail") is FactTeamLineupsDetailSchema
    assert get_output_schema("fact_team_matchups") is FactTeamMatchupsSchema


def test_team_family_schemas_validate_representative_rows() -> None:
    lineup = pl.DataFrame(
        {
            "group_set": ["Lineups"],
            "group_id": ["1627759-1628369-1628400-1629057-203954"],
            "group_name": ["Starter Group"],
            "team_id": [1610612738],
            "team_abbreviation": ["BOS"],
            "gp": [34],
            "w": [22],
            "l": [12],
            "w_pct": [0.647],
            "min": [315.4],
            "fgm": [128],
            "fga": [250],
            "fg_pct": [0.512],
            "fg3m": [51],
            "fg3a": [130],
            "fg3_pct": [0.392],
            "ftm": [44],
            "fta": [56],
            "ft_pct": [0.786],
            "oreb": [31],
            "dreb": [92],
            "reb": [123],
            "ast": [78],
            "tov": [29],
            "stl": [18],
            "blk": [11],
            "blka": [9],
            "pf": [52],
            "pfd": [47],
            "pts": [351],
            "plus_minus": [42.0],
            "gp_rank": [7],
            "w_rank": [5],
            "l_rank": [18],
            "w_pct_rank": [6],
            "min_rank": [4],
            "fgm_rank": [3],
            "fga_rank": [5],
            "fg_pct_rank": [2],
            "fg3m_rank": [2],
            "fg3a_rank": [4],
            "fg3_pct_rank": [3],
            "ftm_rank": [8],
            "fta_rank": [10],
            "ft_pct_rank": [12],
            "oreb_rank": [16],
            "dreb_rank": [5],
            "reb_rank": [7],
            "ast_rank": [4],
            "tov_rank": [20],
            "stl_rank": [14],
            "blk_rank": [12],
            "blka_rank": [11],
            "pf_rank": [19],
            "pfd_rank": [13],
            "pts_rank": [3],
            "plus_minus_rank": [2],
            "season_year": ["2024-25"],
            "season_type": ["Regular Season"],
        }
    )
    pass_row = pl.DataFrame(
        {
            "team_id": [1610612738],
            "team_name": ["Boston Celtics"],
            "pass_type": ["made"],
            "g": [82],
            "pass_from": ["Jayson Tatum"],
            "pass_to": [None],
            "pass_teammate_player_id": [1627759],
            "frequency": [0.148],
            "pass": [312],
            "ast": [28],
            "fgm": [41],
            "fga": [88],
            "fg_pct": [0.466],
            "fg2m": [23],
            "fg2a": [40],
            "fg2_pct": [0.575],
            "fg3m": [18],
            "fg3a": [48],
            "fg3_pct": [0.375],
            "season_type": ["Regular Season"],
        }
    )
    reb_row = pl.DataFrame(
        {
            "team_id": [1610612738],
            "team_name": ["Boston Celtics"],
            "sort_order": [1],
            "g": [82],
            "reb_num_contesting_range": ["0-2"],
            "reb_frequency": [0.314],
            "oreb": [94],
            "dreb": [228],
            "reb": [322],
            "c_oreb": [28],
            "c_dreb": [90],
            "c_reb": [118],
            "c_reb_pct": [0.366],
            "uc_oreb": [66],
            "uc_dreb": [138],
            "uc_reb": [204],
            "uc_reb_pct": [0.634],
            "season_type": ["Regular Season"],
        }
    )
    shots_row = pl.DataFrame(
        {
            "team_id": [1610612738],
            "team_name": ["Boston Celtics"],
            "sort_order": [1],
            "g": [82],
            "close_def_dist_range": ["6+ Feet - Wide Open"],
            "fga_frequency": [0.286],
            "fgm": [205],
            "fga": [420],
            "fg_pct": [0.488],
            "efg_pct": [0.612],
            "fg2a_frequency": [0.382],
            "fg2m": [88],
            "fg2a": [160],
            "fg2_pct": [0.55],
            "fg3a_frequency": [0.618],
            "fg3m": [117],
            "fg3a": [260],
            "fg3_pct": [0.45],
            "season_type": ["Regular Season"],
        }
    )
    matchup_row = pl.DataFrame(
        {
            "group_set": ["OnOffCourt"],
            "group_value": [None],
            "title_description": [None],
            "description": [None],
            "team_id": [1610612738],
            "team_abbreviation": ["BOS"],
            "team_name": ["Celtics"],
            "player_id": [201939],
            "player_name": ["Stephen Curry"],
            "vs_player_id": [2544],
            "vs_player_name": ["LeBron James"],
            "court_status": ["On"],
            "gp": [5],
            "w": [3],
            "l": [2],
            "w_pct": [0.6],
            "min": [18.4],
            "fgm": [10.0],
            "fga": [22.0],
            "fg_pct": [0.455],
            "fg3m": [4.0],
            "fg3a": [11.0],
            "fg3_pct": [0.364],
            "ftm": [3.0],
            "fta": [4.0],
            "ft_pct": [0.75],
            "oreb": [1.0],
            "dreb": [7.0],
            "reb": [8.0],
            "ast": [7.0],
            "tov": [2.0],
            "stl": [1.0],
            "blk": [0.0],
            "blka": [0.0],
            "pf": [2.0],
            "pfd": [4.0],
            "pts": [27.0],
            "plus_minus": [7.0],
            "nba_fantasy_pts": [44.5],
            "dd2": [1.0],
            "td3": [0.0],
            "gp_rank": [4],
            "w_rank": [5],
            "l_rank": [10],
            "w_pct_rank": [6],
            "min_rank": [7],
            "fgm_rank": [8],
            "fga_rank": [9],
            "fg_pct_rank": [11],
            "fg3m_rank": [3],
            "fg3a_rank": [4],
            "fg3_pct_rank": [12],
            "ftm_rank": [13],
            "fta_rank": [14],
            "ft_pct_rank": [15],
            "oreb_rank": [16],
            "dreb_rank": [17],
            "reb_rank": [18],
            "ast_rank": [19],
            "tov_rank": [20],
            "stl_rank": [21],
            "blk_rank": [22],
            "blka_rank": [23],
            "pf_rank": [24],
            "pfd_rank": [25],
            "pts_rank": [26],
            "plus_minus_rank": [27],
            "nba_fantasy_pts_rank": [28],
            "dd2_rank": [29],
            "td3_rank": [30],
            "cfid": ["7"],
            "cfparams": ["TEAM_ID=1610612738&VS_PLAYER_ID=2544"],
        }
    )
    shot_split_row = pl.DataFrame(
        {
            "group_set": ["ShotArea"],
            "group_value": ["Paint"],
            "title_description": [None],
            "description": [None],
            "team_id": [1610612738],
            "team_abbreviation": ["BOS"],
            "team_name": ["Celtics"],
            "vs_player_id": [2544],
            "vs_player_name": ["LeBron James"],
            "court_status": ["Off"],
            "cfid": ["7"],
            "cfparams": ["TEAM_ID=1610612738&VS_PLAYER_ID=2544"],
            "fgm": [12.0],
            "fga": [24.0],
            "fg_pct": [0.5],
        }
    )
    team_matchups = matchup_row.with_columns(matchup_type=pl.lit("team_vs_player"))
    team_lineups = lineup.select(
        "group_set",
        "group_id",
        "group_name",
        "gp",
        "w",
        "l",
        "w_pct",
        "min",
        "fgm",
        "fga",
        "fg_pct",
        "fg3m",
        "fg3a",
        "fg3_pct",
        "ftm",
        "fta",
        "ft_pct",
        "oreb",
        "dreb",
        "reb",
        "ast",
        "tov",
        "stl",
        "blk",
        "blka",
        "pf",
        "pfd",
        "pts",
        "plus_minus",
        "gp_rank",
        "w_rank",
        "l_rank",
        "w_pct_rank",
        "min_rank",
        "fgm_rank",
        "fga_rank",
        "fg_pct_rank",
        "fg3m_rank",
        "fg3a_rank",
        "fg3_pct_rank",
        "ftm_rank",
        "fta_rank",
        "ft_pct_rank",
        "oreb_rank",
        "dreb_rank",
        "reb_rank",
        "ast_rank",
        "tov_rank",
        "stl_rank",
        "blk_rank",
        "blka_rank",
        "pf_rank",
        "pfd_rank",
        "pts_rank",
        "plus_minus_rank",
        "season_type",
    )

    assert StagingTeamLineupsSchema.validate(lineup).shape[0] == 1
    assert StagingTeamLineupsOverallSchema.validate(lineup).shape[0] == 1
    assert StagingTeamPtPassSchema.validate(pass_row).shape[0] == 1
    assert StagingTeamPtPassReceivedSchema.validate(pass_row).shape[0] == 1
    assert StagingTeamPtRebSchema.validate(reb_row).shape[0] == 1
    assert StagingTeamPtShotsSchema.validate(shots_row).shape[0] == 1
    assert StagingTeamVsPlayerSchema.validate(matchup_row).shape[0] == 1
    assert StagingTeamAndPlayersVsSchema.validate(matchup_row).shape[0] == 1
    assert StagingTapvpTeamOnSchema.validate(matchup_row).shape[0] == 1
    assert StagingTvpShotAreaOffSchema.validate(shot_split_row).shape[0] == 1
    assert FactTeamLineupsDetailSchema.validate(team_lineups).shape[0] == 1
    assert FactTeamMatchupsSchema.validate(team_matchups).shape[0] == 1
