from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from typing import TYPE_CHECKING

from nbadb.extract.registry import registry
from nbadb.orchestrate.transformers import discover_all_transformers
from nbadb.schemas.registry import _star_schema_registry

if TYPE_CHECKING:
    from pathlib import Path


@dataclass(frozen=True, slots=True)
class SiteMetric:
    label: str
    value: str
    note: str


_TRANSFORM_FAMILY_PREFIXES: tuple[tuple[str, str], ...] = (
    ("dimensions", "dim_"),
    ("facts", "fact_"),
    ("bridges", "bridge_"),
    ("aggregates", "agg_"),
    ("analytics", "analytics_"),
)
_SCD_TYPE_2_DIMENSIONS: tuple[str, ...] = ("dim_player", "dim_team_history")


def resolve_site_metrics_output_path(docs_root: Path) -> Path:
    docs_root = docs_root.resolve()
    if docs_root.name == "docs" and docs_root.parent.name == "content":
        return docs_root.parent.parent / "lib" / "site-metrics.generated.ts"
    return docs_root / "_generated" / "site-metrics.generated.ts"


def _count_docs_pages(docs_root: Path) -> int:
    return sum(1 for path in docs_root.rglob("*.mdx") if path.is_file())


def _discover_transform_outputs() -> set[str]:
    return {transformer.output_table for transformer in discover_all_transformers()}


def _discover_transform_family_counts() -> dict[str, int]:
    transform_outputs = _discover_transform_outputs()
    return {
        family: sum(1 for output_table in transform_outputs if output_table.startswith(prefix))
        for family, prefix in _TRANSFORM_FAMILY_PREFIXES
    }


def _discover_public_model_family_counts() -> dict[str, int]:
    public_outputs = _star_schema_registry().keys()
    return {
        family: sum(1 for output_table in public_outputs if output_table.startswith(prefix))
        for family, prefix in _TRANSFORM_FAMILY_PREFIXES
    }


def _count_tables() -> int:
    return len(_star_schema_registry())


def _count_endpoints() -> int:
    registry.discover()
    return registry.count


def build_site_metrics(docs_root: Path) -> list[SiteMetric]:
    family_counts = _discover_transform_family_counts()
    derived_output_count = family_counts["aggregates"] + family_counts["analytics"]

    return [
        SiteMetric(
            label="Models",
            value=str(_count_tables()),
            note="discovered star-schema models",
        ),
        SiteMetric(
            label="Extractors",
            value=str(_count_endpoints()),
            note="registered extractor wrappers",
        ),
        SiteMetric(
            label="Docs Pages",
            value=str(_count_docs_pages(docs_root)),
            note="authored + generated MDX routes",
        ),
        SiteMetric(
            label="Derived Models",
            value=str(derived_output_count),
            note="agg_* and analytics_* outputs",
        ),
    ]


def generate_site_metrics_module(docs_root: Path) -> str:
    metrics = build_site_metrics(docs_root)
    family_counts = _discover_public_model_family_counts()
    inventory = {
        "modelCount": str(_count_tables()),
        "extractorCount": str(_count_endpoints()),
        "docsPageCount": str(_count_docs_pages(docs_root)),
        "publicOutputCount": str(sum(family_counts.values())),
        "derivedOutputCount": str(family_counts["aggregates"] + family_counts["analytics"]),
        "tableFamilyCounts": {key: str(value) for key, value in family_counts.items()},
        "scdType2Dimensions": list(_SCD_TYPE_2_DIMENSIONS),
    }
    entries = ",\n".join(f"  {json.dumps(asdict(metric), ensure_ascii=True)}" for metric in metrics)
    return (
        "// Generated by `uv run nbadb docs-autogen --docs-root docs/content/docs`.\n"
        "// Do not edit by hand.\n"
        'import type { SiteMetric } from "@/lib/site-config";\n\n'
        f"export const siteInventory = {json.dumps(inventory, ensure_ascii=True)} as const;\n\n"
        "export const siteMetrics: SiteMetric[] = [\n"
        f"{entries}\n"
        "];\n"
    )
