// Generated by `uv run nbadb docs-autogen --docs-root docs/content/docs`.
// Do not edit by hand.
import type { SiteMetric } from "@/lib/site-config";

export const siteInventory = {
  modelCount: "254",
  extractorCount: "152",
  docsPageCount: "51",
  publicOutputCount: "254",
  derivedOutputCount: "33",
  tableFamilyCounts: {
    dimensions: "18",
    facts: "197",
    bridges: "6",
    aggregates: "19",
    analytics: "14",
  },
  scdType2Dimensions: ["dim_player", "dim_team_history"],
} as const;

export const siteMetrics: SiteMetric[] = [
  { label: "Models", value: "254", note: "discovered star-schema models" },
  { label: "Extractors", value: "152", note: "registered extractor wrappers" },
  { label: "Docs Pages", value: "51", note: "authored + generated MDX routes" },
  {
    label: "Derived Models",
    value: "33",
    note: "agg_* and analytics_* outputs",
  },
];
