// Generated by `uv run nbadb docs-autogen --docs-root docs/content/docs`.
// Do not edit by hand.
import type { SiteMetric } from "@/lib/site-config";

export const siteInventory = {"modelCount": "118", "extractorCount": "151", "docsPageCount": "51", "publicOutputCount": "118", "derivedOutputCount": "31", "tableFamilyCounts": {"dimensions": "18", "facts": "64", "bridges": "5", "aggregates": "19", "analytics": "12"}, "scdType2Dimensions": ["dim_player", "dim_team_history"]} as const;

export const siteMetrics: SiteMetric[] = [
  {"label": "Models", "value": "118", "note": "discovered star-schema models"},
  {"label": "Extractors", "value": "151", "note": "registered extractor wrappers"},
  {"label": "Docs Pages", "value": "51", "note": "authored + generated MDX routes"},
  {"label": "Derived Models", "value": "31", "note": "agg_* and analytics_* outputs"}
];
