// Generated by `uv run nbadb docs-autogen --docs-root docs/content/docs`.
// Do not edit by hand.
import type { SiteMetric } from "@/lib/site-config";

export const siteMetrics: SiteMetric[] = [
  {"label": "Models", "value": "96", "note": "discovered star-schema models"},
  {"label": "Extractors", "value": "151", "note": "registered extractor wrappers"},
  {"label": "Docs Pages", "value": "49", "note": "authored + generated MDX routes"},
  {"label": "Derived Models", "value": "28", "note": "agg_* and analytics_* outputs"}
];
