from __future__ import annotations

import pandera.polars as pa

from nbadb.schemas.base import BaseSchema


class FactTeamLineupsOverallSchema(BaseSchema):
    group_set: str = pa.Field(metadata={"description": "Lineup grouping set"})
    group_id: str = pa.Field(metadata={"description": "Lineup group identifier"})
    group_name: str | None = pa.Field(nullable=True)
    gp: int | None = pa.Field(nullable=True, ge=0)
    w: int | None = pa.Field(nullable=True, ge=0)
    l: int | None = pa.Field(nullable=True, ge=0)  # noqa: E741
    w_pct: float | None = pa.Field(nullable=True, ge=0.0)
    min: float | None = pa.Field(nullable=True, ge=0.0)
    fgm: int | None = pa.Field(nullable=True, ge=0)
    fga: int | None = pa.Field(nullable=True, ge=0)
    fg_pct: float | None = pa.Field(nullable=True, ge=0.0)
    fg3m: int | None = pa.Field(nullable=True, ge=0)
    fg3a: int | None = pa.Field(nullable=True, ge=0)
    fg3_pct: float | None = pa.Field(nullable=True, ge=0.0)
    ftm: int | None = pa.Field(nullable=True, ge=0)
    fta: int | None = pa.Field(nullable=True, ge=0)
    ft_pct: float | None = pa.Field(nullable=True, ge=0.0)
    oreb: int | None = pa.Field(nullable=True, ge=0)
    dreb: int | None = pa.Field(nullable=True, ge=0)
    reb: int | None = pa.Field(nullable=True, ge=0)
    ast: int | None = pa.Field(nullable=True, ge=0)
    tov: int | None = pa.Field(nullable=True, ge=0)
    stl: int | None = pa.Field(nullable=True, ge=0)
    blk: int | None = pa.Field(nullable=True, ge=0)
    blka: int | None = pa.Field(nullable=True, ge=0)
    pf: int | None = pa.Field(nullable=True, ge=0)
    pfd: int | None = pa.Field(nullable=True, ge=0)
    pts: int | None = pa.Field(nullable=True, ge=0)
    plus_minus: float | None = pa.Field(nullable=True)
    gp_rank: int | None = pa.Field(nullable=True, ge=0)
    w_rank: int | None = pa.Field(nullable=True, ge=0)
    l_rank: int | None = pa.Field(nullable=True, ge=0)  # noqa: E741
    w_pct_rank: int | None = pa.Field(nullable=True, ge=0)
    min_rank: int | None = pa.Field(nullable=True, ge=0)
    fgm_rank: int | None = pa.Field(nullable=True, ge=0)
    fga_rank: int | None = pa.Field(nullable=True, ge=0)
    fg_pct_rank: int | None = pa.Field(nullable=True, ge=0)
    fg3m_rank: int | None = pa.Field(nullable=True, ge=0)
    fg3a_rank: int | None = pa.Field(nullable=True, ge=0)
    fg3_pct_rank: int | None = pa.Field(nullable=True, ge=0)
    ftm_rank: int | None = pa.Field(nullable=True, ge=0)
    fta_rank: int | None = pa.Field(nullable=True, ge=0)
    ft_pct_rank: int | None = pa.Field(nullable=True, ge=0)
    oreb_rank: int | None = pa.Field(nullable=True, ge=0)
    dreb_rank: int | None = pa.Field(nullable=True, ge=0)
    reb_rank: int | None = pa.Field(nullable=True, ge=0)
    ast_rank: int | None = pa.Field(nullable=True, ge=0)
    tov_rank: int | None = pa.Field(nullable=True, ge=0)
    stl_rank: int | None = pa.Field(nullable=True, ge=0)
    blk_rank: int | None = pa.Field(nullable=True, ge=0)
    blka_rank: int | None = pa.Field(nullable=True, ge=0)
    pf_rank: int | None = pa.Field(nullable=True, ge=0)
    pfd_rank: int | None = pa.Field(nullable=True, ge=0)
    pts_rank: int | None = pa.Field(nullable=True, ge=0)
    plus_minus_rank: int | None = pa.Field(nullable=True, ge=0)
    season_type: str = pa.Field(
        metadata={"description": "Season type (Regular Season, Playoffs, etc.)"}
    )


class FactTeamPtRebDetailSchema(BaseSchema):
    team_id: int = pa.Field(gt=0)
    team_name: str | None = pa.Field(nullable=True)
    sort_order: int | None = pa.Field(nullable=True, ge=0)
    g: int | None = pa.Field(nullable=True, ge=0)
    reb_num_contesting_range: str | None = pa.Field(nullable=True)
    reb_frequency: float | None = pa.Field(nullable=True, ge=0.0)
    oreb: int | None = pa.Field(nullable=True, ge=0)
    dreb: int | None = pa.Field(nullable=True, ge=0)
    reb: int | None = pa.Field(nullable=True, ge=0)
    c_oreb: int | None = pa.Field(nullable=True, ge=0)
    c_dreb: int | None = pa.Field(nullable=True, ge=0)
    c_reb: int | None = pa.Field(nullable=True, ge=0)
    c_reb_pct: float | None = pa.Field(nullable=True, ge=0.0)
    uc_oreb: int | None = pa.Field(nullable=True, ge=0)
    uc_dreb: int | None = pa.Field(nullable=True, ge=0)
    uc_reb: int | None = pa.Field(nullable=True, ge=0)
    uc_reb_pct: float | None = pa.Field(nullable=True, ge=0.0)
    season_type: str = pa.Field(
        metadata={"description": "Season type (Regular Season, Playoffs, etc.)"}
    )


class FactTeamPtShotsDetailSchema(BaseSchema):
    team_id: int = pa.Field(gt=0)
    team_name: str | None = pa.Field(nullable=True)
    sort_order: int | None = pa.Field(nullable=True, ge=0)
    g: int | None = pa.Field(nullable=True, ge=0)
    close_def_dist_range: str | None = pa.Field(nullable=True)
    fga_frequency: float | None = pa.Field(nullable=True, ge=0.0)
    fgm: int | None = pa.Field(nullable=True, ge=0)
    fga: int | None = pa.Field(nullable=True, ge=0)
    fg_pct: float | None = pa.Field(nullable=True, ge=0.0)
    efg_pct: float | None = pa.Field(nullable=True, ge=0.0)
    fg2a_frequency: float | None = pa.Field(nullable=True, ge=0.0)
    fg2m: int | None = pa.Field(nullable=True, ge=0)
    fg2a: int | None = pa.Field(nullable=True, ge=0)
    fg2_pct: float | None = pa.Field(nullable=True, ge=0.0)
    fg3a_frequency: float | None = pa.Field(nullable=True, ge=0.0)
    fg3m: int | None = pa.Field(nullable=True, ge=0)
    fg3a: int | None = pa.Field(nullable=True, ge=0)
    fg3_pct: float | None = pa.Field(nullable=True, ge=0.0)
    season_type: str = pa.Field(
        metadata={"description": "Season type (Regular Season, Playoffs, etc.)"}
    )


class FactTeamPtTrackingSchema(BaseSchema):
    tracking_type: str = pa.Field(isin=["pass", "pass_received", "rebound", "shots"])
    team_id: int = pa.Field(gt=0)
    team_name: str | None = pa.Field(nullable=True)
    pass_type: str | None = pa.Field(nullable=True)
    g: int | None = pa.Field(nullable=True, ge=0)
    pass_from: str | None = pa.Field(nullable=True)
    pass_to: str | None = pa.Field(nullable=True)
    pass_teammate_player_id: int | None = pa.Field(nullable=True, gt=0)
    frequency: float | None = pa.Field(nullable=True, ge=0.0)
    pass_: int | None = pa.Field(nullable=True, ge=0, alias="pass")
    ast: int | None = pa.Field(nullable=True, ge=0)
    fgm: int | None = pa.Field(nullable=True, ge=0)
    fga: int | None = pa.Field(nullable=True, ge=0)
    fg_pct: float | None = pa.Field(nullable=True, ge=0.0)
    fg2m: int | None = pa.Field(nullable=True, ge=0)
    fg2a: int | None = pa.Field(nullable=True, ge=0)
    fg2_pct: float | None = pa.Field(nullable=True, ge=0.0)
    fg3m: int | None = pa.Field(nullable=True, ge=0)
    fg3a: int | None = pa.Field(nullable=True, ge=0)
    fg3_pct: float | None = pa.Field(nullable=True, ge=0.0)
    sort_order: int | None = pa.Field(nullable=True, ge=0)
    reb_num_contesting_range: str | None = pa.Field(nullable=True)
    reb_frequency: float | None = pa.Field(nullable=True, ge=0.0)
    oreb: int | None = pa.Field(nullable=True, ge=0)
    dreb: int | None = pa.Field(nullable=True, ge=0)
    reb: int | None = pa.Field(nullable=True, ge=0)
    c_oreb: int | None = pa.Field(nullable=True, ge=0)
    c_dreb: int | None = pa.Field(nullable=True, ge=0)
    c_reb: int | None = pa.Field(nullable=True, ge=0)
    c_reb_pct: float | None = pa.Field(nullable=True, ge=0.0)
    uc_oreb: int | None = pa.Field(nullable=True, ge=0)
    uc_dreb: int | None = pa.Field(nullable=True, ge=0)
    uc_reb: int | None = pa.Field(nullable=True, ge=0)
    uc_reb_pct: float | None = pa.Field(nullable=True, ge=0.0)
    close_def_dist_range: str | None = pa.Field(nullable=True)
    fga_frequency: float | None = pa.Field(nullable=True, ge=0.0)
    efg_pct: float | None = pa.Field(nullable=True, ge=0.0)
    fg2a_frequency: float | None = pa.Field(nullable=True, ge=0.0)
    fg3a_frequency: float | None = pa.Field(nullable=True, ge=0.0)
    season_type: str = pa.Field(
        metadata={"description": "Season type (Regular Season, Playoffs, etc.)"}
    )
