from __future__ import annotations

from typing import Any, ClassVar

import polars as pl

from nbadb.transform.base import BaseTransformer
from nbadb.transform.facts._comparison_detail import (
    ComparisonDetailSpec,
    consolidate_detail_family,
)

_TEAM_MATCHUP_DETAIL_SPECS: tuple[ComparisonDetailSpec, ...] = (
    ComparisonDetailSpec(
        "stg_tvp_on_off_court",
        labels={"detail_source": "team_vs_player", "detail_variant": "on_off_court"},
    ),
    ComparisonDetailSpec(
        "stg_tvp_overall",
        labels={"detail_source": "team_vs_player", "detail_variant": "overall"},
    ),
    ComparisonDetailSpec(
        "stg_tvp_vs_player_overall",
        labels={"detail_source": "team_vs_player", "detail_variant": "vs_player_overall"},
    ),
    ComparisonDetailSpec(
        "stg_tapvp_players_vs",
        labels={"detail_source": "team_and_players_vs", "detail_variant": "players_vs_players"},
    ),
    ComparisonDetailSpec(
        "stg_tapvp_team_off",
        labels={
            "detail_source": "team_and_players_vs",
            "detail_variant": "team_players_vs_players_off",
        },
    ),
    ComparisonDetailSpec(
        "stg_tapvp_team_on",
        labels={
            "detail_source": "team_and_players_vs",
            "detail_variant": "team_players_vs_players_on",
        },
    ),
    ComparisonDetailSpec(
        "stg_tapvp_team_vs",
        labels={"detail_source": "team_and_players_vs", "detail_variant": "team_vs_players"},
    ),
    ComparisonDetailSpec(
        "stg_tapvp_team_vs_off",
        labels={
            "detail_source": "team_and_players_vs",
            "detail_variant": "team_vs_players_off",
        },
    ),
)

_OUTPUT_SCHEMA: dict[str, Any] = {
    "detail_source": pl.Utf8,
    "detail_variant": pl.Utf8,
    "group_set": pl.Utf8,
    "group_value": pl.Utf8,
    "title_description": pl.Utf8,
    "description": pl.Utf8,
    "team_id": pl.Int64,
    "team_abbreviation": pl.Utf8,
    "team_name": pl.Utf8,
    "player_id": pl.Int64,
    "player_name": pl.Utf8,
    "vs_player_id": pl.Int64,
    "vs_player_name": pl.Utf8,
    "court_status": pl.Utf8,
    "gp": pl.Int64,
    "w": pl.Int64,
    "l": pl.Int64,
    "w_pct": pl.Float64,
    "min": pl.Float64,
    "fgm": pl.Float64,
    "fga": pl.Float64,
    "fg_pct": pl.Float64,
    "fg3m": pl.Float64,
    "fg3a": pl.Float64,
    "fg3_pct": pl.Float64,
    "ftm": pl.Float64,
    "fta": pl.Float64,
    "ft_pct": pl.Float64,
    "oreb": pl.Float64,
    "dreb": pl.Float64,
    "reb": pl.Float64,
    "ast": pl.Float64,
    "tov": pl.Float64,
    "stl": pl.Float64,
    "blk": pl.Float64,
    "blka": pl.Float64,
    "pf": pl.Float64,
    "pfd": pl.Float64,
    "pts": pl.Float64,
    "plus_minus": pl.Float64,
    "nba_fantasy_pts": pl.Float64,
    "dd2": pl.Float64,
    "td3": pl.Float64,
    "gp_rank": pl.Int64,
    "w_rank": pl.Int64,
    "l_rank": pl.Int64,
    "w_pct_rank": pl.Int64,
    "min_rank": pl.Int64,
    "fgm_rank": pl.Int64,
    "fga_rank": pl.Int64,
    "fg_pct_rank": pl.Int64,
    "fg3m_rank": pl.Int64,
    "fg3a_rank": pl.Int64,
    "fg3_pct_rank": pl.Int64,
    "ftm_rank": pl.Int64,
    "fta_rank": pl.Int64,
    "ft_pct_rank": pl.Int64,
    "oreb_rank": pl.Int64,
    "dreb_rank": pl.Int64,
    "reb_rank": pl.Int64,
    "ast_rank": pl.Int64,
    "tov_rank": pl.Int64,
    "stl_rank": pl.Int64,
    "blk_rank": pl.Int64,
    "blka_rank": pl.Int64,
    "pf_rank": pl.Int64,
    "pfd_rank": pl.Int64,
    "pts_rank": pl.Int64,
    "plus_minus_rank": pl.Int64,
    "nba_fantasy_pts_rank": pl.Int64,
    "dd2_rank": pl.Int64,
    "td3_rank": pl.Int64,
    "cfid": pl.Utf8,
    "cfparams": pl.Utf8,
}


class FactTeamMatchupsDetailTransformer(BaseTransformer):
    output_table: ClassVar[str] = "fact_team_matchups_detail"
    depends_on: ClassVar[list[str]] = [spec.staging_key for spec in _TEAM_MATCHUP_DETAIL_SPECS]

    def transform(self, staging: dict[str, pl.LazyFrame]) -> pl.DataFrame:
        return consolidate_detail_family(
            staging,
            specs=_TEAM_MATCHUP_DETAIL_SPECS,
            output_schema=_OUTPUT_SCHEMA,
            passthrough_columns=(
                "group_set",
                "group_value",
                "title_description",
                "description",
                "team_id",
                "team_abbreviation",
                "team_name",
                "player_id",
                "player_name",
                "vs_player_id",
                "vs_player_name",
                "court_status",
                "gp",
                "w",
                "l",
                "w_pct",
                "min",
                "fgm",
                "fga",
                "fg_pct",
                "fg3m",
                "fg3a",
                "fg3_pct",
                "ftm",
                "fta",
                "ft_pct",
                "oreb",
                "dreb",
                "reb",
                "ast",
                "tov",
                "stl",
                "blk",
                "blka",
                "pf",
                "pfd",
                "pts",
                "plus_minus",
                "nba_fantasy_pts",
                "dd2",
                "td3",
                "gp_rank",
                "w_rank",
                "l_rank",
                "w_pct_rank",
                "min_rank",
                "fgm_rank",
                "fga_rank",
                "fg_pct_rank",
                "fg3m_rank",
                "fg3a_rank",
                "fg3_pct_rank",
                "ftm_rank",
                "fta_rank",
                "ft_pct_rank",
                "oreb_rank",
                "dreb_rank",
                "reb_rank",
                "ast_rank",
                "tov_rank",
                "stl_rank",
                "blk_rank",
                "blka_rank",
                "pf_rank",
                "pfd_rank",
                "pts_rank",
                "plus_minus_rank",
                "nba_fantasy_pts_rank",
                "dd2_rank",
                "td3_rank",
                "cfid",
                "cfparams",
            ),
            sort_columns=(
                "detail_source",
                "detail_variant",
                "team_id",
                "player_id",
                "vs_player_id",
                "description",
                "group_value",
            ),
        )
